---
resources:
- name: resource-concourse-echo
  type: git
  source:
    branch: master
    uri: https://github.com/sadema/concourse-echo.git

- name: deploy-cf
  type: cf
  source:
    api: ((api_cf))
    username: ((username_cf))
    password: ((password_cf))
    organization: ((organization_cf))
    space: ((space_cf))
    skip_cert_check: true

jobs:
- name: run-unit-tests
  public: true
  plan:
  - get: resource-concourse-echo
    trigger: false
  - task: unit-tests
    file: resource-concourse-echo/ci/task_run_unittests.yml

- name: build
  public: false
  plan:
    - get: resource-concourse-echo
      passed: [run-unit-tests]
      trigger: true
    - task: build-code
      file: resource-concourse-echo/ci/task_buildcode.yml
    - put: deploy-cf
      params:
        manifest: resource-concourse-echo/ci/cf_manifest.yml
        path: artifacts/*.jar
